language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - php vendor/bin/codecept run unit -c codeception.yml --coverage-xml

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v